### ISSUE TITLE
cordova app 修改代码之后前端并没有获得任何更新

### ISSUE THREAD

**Issue by cy920820** [lisong/code-push-cordova-demo-app#1]
后端自己在阿里云上搭建的code push server
前端按照 这个demo的步骤提交代码，打开app 没有得到任何更新

**Comment by cy920820** [comment]
更新上传截图
![image](https://user-images.githubusercontent.com/21211512/47965627-5ddefd80-e084-11e8-94c1-b58655d2f20d.png)

**Comment by lisong** [comment]
保证app的版本号和codepushserver发的版本号一致，查看请求checkupdate返回的数据

**Comment by cy920820** [comment]
谢谢深夜回答！！！
首先版本号没有改动过，都是v1.0.0 ，
然后我打开app之后出现了 官方api调出的dialog更新，我点击INSTALL ，控制台报错，更新dialog截图如下：
![image](https://user-images.githubusercontent.com/21211512/47966563-d21e9e80-e08e-11e8-82b1-1fb6641c4d0a.png)
报错截图如下
![image](https://user-images.githubusercontent.com/21211512/47966570-e6fb3200-e08e-11e8-94f3-a2ae5a4f119e.png)

**Comment by lisong** [comment]
downloadurl配置有问题

**Comment by cy920820** [comment]
@lisong 非常感谢提供的建议，这边后端在download地址做了代理，协议用的是http 和 config.xml配置的地址协议不一样，现在已经修复，谢谢了 ！
